name: alphabet_green_energy
description: Alphabet Green Energy App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  get: ^4.6.5
  flutter_otp_text_field: ^1.1.1
  image_picker: ^0.8.7
  path_provider: ^2.0.14
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  dropdown_search: ^5.0.6
  file_picker: ^5.2.6
  firebase_storage: ^11.0.16
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.4
  email_validator:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/ag-logo.svg
  image_dark: assets/images/ag-logo.svg

  android_12:
    image: assets/images/ag-logo.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/ag-logo.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/forgot_password/
    - assets/logo/