name: alphabet_green_energy
description: Alphabet Green Energy App
publish_to: 'none'
version: 20.0.0+20

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.2.19
  get: ^4.6.5
  flutter_otp_text_field: ^1.1.1
  image_picker: ^1.0.2
  path_provider: ^2.0.14
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.9.0
  dropdown_search: ^5.0.6
  file_picker: ^8.0.0+1
  firebase_storage: ^11.0.16
  shared_preferences: ^2.1.0
  connectivity_plus: ^6.0.1
  email_validator:
  url_launcher:
  flutter_launcher_icons: ^0.13.1
  firebase_app_check: ^0.2.1+8
  location: ^5.0.3
  share_plus: ^8.0.2
  archive: ^3.4.10
  http: ^1.2.1
  csv:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/ag-logo.png"
  min_sdk_android: 22 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/ag-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/ag-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/ag-logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logo/splash.png
  image_dark: assets/logo/splash.png

  android_12:
    image: assets/logo/splash.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/logo/splash.png
    icon_background_color_dark: "#272727"

  web:
    image: assets/logo/splash.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/logo/splash.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/forgot_password/
    - assets/zipData.json