/// Phone country codes, ordered with India first (the app's primary user
/// base and the default selection) and the United States second, then the
/// rest of the world alphabetically by name. Names/dial codes sourced from
/// the country_code_picker package's data (country_codes.dart + i18n/en.json
/// merged — that package's main list has non-English names for some
/// countries, so this draws names from its English locale file instead),
/// with a few multi-name entries (US/GB/RU/PS) resolved to their common
/// English name.
class CountryCode {
  final String name;
  final String iso2;
  final String dialCode;

  const CountryCode({
    required this.name,
    required this.iso2,
    required this.dialCode,
  });
}

const List<CountryCode> kCountryCodes = [
  CountryCode(name: 'India', iso2: 'IN', dialCode: '+91'), // default
  CountryCode(name: 'United States', iso2: 'US', dialCode: '+1'),
  CountryCode(name: 'Afghanistan', iso2: 'AF', dialCode: '+93'),
  CountryCode(name: 'Albania', iso2: 'AL', dialCode: '+355'),
  CountryCode(name: 'Algeria', iso2: 'DZ', dialCode: '+213'),
  CountryCode(name: 'American Samoa', iso2: 'AS', dialCode: '+1684'),
  CountryCode(name: 'Andorra', iso2: 'AD', dialCode: '+376'),
  CountryCode(name: 'Angola', iso2: 'AO', dialCode: '+244'),
  CountryCode(name: 'Anguilla', iso2: 'AI', dialCode: '+1264'),
  CountryCode(name: 'Antarctica', iso2: 'AQ', dialCode: '+672'),
  CountryCode(name: 'Antigua and Barbuda', iso2: 'AG', dialCode: '+1268'),
  CountryCode(name: 'Argentina', iso2: 'AR', dialCode: '+54'),
  CountryCode(name: 'Armenia', iso2: 'AM', dialCode: '+374'),
  CountryCode(name: 'Aruba', iso2: 'AW', dialCode: '+297'),
  CountryCode(name: 'Australia', iso2: 'AU', dialCode: '+61'),
  CountryCode(name: 'Austria', iso2: 'AT', dialCode: '+43'),
  CountryCode(name: 'Azerbaijan', iso2: 'AZ', dialCode: '+994'),
  CountryCode(name: 'Bahamas', iso2: 'BS', dialCode: '+1242'),
  CountryCode(name: 'Bahrain', iso2: 'BH', dialCode: '+973'),
  CountryCode(name: 'Bangladesh', iso2: 'BD', dialCode: '+880'),
  CountryCode(name: 'Barbados', iso2: 'BB', dialCode: '+1246'),
  CountryCode(name: 'Belarus', iso2: 'BY', dialCode: '+375'),
  CountryCode(name: 'Belgium', iso2: 'BE', dialCode: '+32'),
  CountryCode(name: 'Belize', iso2: 'BZ', dialCode: '+501'),
  CountryCode(name: 'Benin', iso2: 'BJ', dialCode: '+229'),
  CountryCode(name: 'Bermuda', iso2: 'BM', dialCode: '+1441'),
  CountryCode(name: 'Bhutan', iso2: 'BT', dialCode: '+975'),
  CountryCode(name: 'Bolivia', iso2: 'BO', dialCode: '+591'),
  CountryCode(name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '+387'),
  CountryCode(name: 'Botswana', iso2: 'BW', dialCode: '+267'),
  CountryCode(name: 'Bouvet Island', iso2: 'BV', dialCode: '+47'),
  CountryCode(name: 'Brazil', iso2: 'BR', dialCode: '+55'),
  CountryCode(name: 'British Indian Ocean Territory', iso2: 'IO', dialCode: '+246'),
  CountryCode(name: 'Brunei Darussalam', iso2: 'BN', dialCode: '+673'),
  CountryCode(name: 'Bulgaria', iso2: 'BG', dialCode: '+359'),
  CountryCode(name: 'Burkina Faso', iso2: 'BF', dialCode: '+226'),
  CountryCode(name: 'Burundi', iso2: 'BI', dialCode: '+257'),
  CountryCode(name: 'Cambodia', iso2: 'KH', dialCode: '+855'),
  CountryCode(name: 'Cameroon', iso2: 'CM', dialCode: '+237'),
  CountryCode(name: 'Canada', iso2: 'CA', dialCode: '+1'),
  CountryCode(name: 'Cape Verde', iso2: 'CV', dialCode: '+238'),
  CountryCode(name: 'Cayman Islands', iso2: 'KY', dialCode: '+1345'),
  CountryCode(name: 'Central African Republic', iso2: 'CF', dialCode: '+236'),
  CountryCode(name: 'Chad', iso2: 'TD', dialCode: '+235'),
  CountryCode(name: 'Chile', iso2: 'CL', dialCode: '+56'),
  CountryCode(name: 'China\'s Mainland', iso2: 'CN', dialCode: '+86'),
  CountryCode(name: 'Christmas Island', iso2: 'CX', dialCode: '+61'),
  CountryCode(name: 'Cocos (Keeling) Islands', iso2: 'CC', dialCode: '+61'),
  CountryCode(name: 'Colombia', iso2: 'CO', dialCode: '+57'),
  CountryCode(name: 'Comoros', iso2: 'KM', dialCode: '+269'),
  CountryCode(name: 'Congo', iso2: 'CG', dialCode: '+242'),
  CountryCode(name: 'Congo, the Democratic Republic of the', iso2: 'CD', dialCode: '+243'),
  CountryCode(name: 'Cook Islands', iso2: 'CK', dialCode: '+682'),
  CountryCode(name: 'Costa Rica', iso2: 'CR', dialCode: '+506'),
  CountryCode(name: 'Cote D\'Ivoire', iso2: 'CI', dialCode: '+225'),
  CountryCode(name: 'Croatia', iso2: 'HR', dialCode: '+385'),
  CountryCode(name: 'Cuba', iso2: 'CU', dialCode: '+53'),
  CountryCode(name: 'Cyprus', iso2: 'CY', dialCode: '+357'),
  CountryCode(name: 'Czech Republic', iso2: 'CZ', dialCode: '+420'),
  CountryCode(name: 'Denmark', iso2: 'DK', dialCode: '+45'),
  CountryCode(name: 'Djibouti', iso2: 'DJ', dialCode: '+253'),
  CountryCode(name: 'Dominica', iso2: 'DM', dialCode: '+1767'),
  CountryCode(name: 'Dominican Republic', iso2: 'DO', dialCode: '+1'),
  CountryCode(name: 'Ecuador', iso2: 'EC', dialCode: '+593'),
  CountryCode(name: 'Egypt', iso2: 'EG', dialCode: '+20'),
  CountryCode(name: 'El Salvador', iso2: 'SV', dialCode: '+503'),
  CountryCode(name: 'Equatorial Guinea', iso2: 'GQ', dialCode: '+240'),
  CountryCode(name: 'Eritrea', iso2: 'ER', dialCode: '+291'),
  CountryCode(name: 'Estonia', iso2: 'EE', dialCode: '+372'),
  CountryCode(name: 'Eswatini', iso2: 'SZ', dialCode: '+268'),
  CountryCode(name: 'Ethiopia', iso2: 'ET', dialCode: '+251'),
  CountryCode(name: 'Falkland Islands (Malvinas)', iso2: 'FK', dialCode: '+500'),
  CountryCode(name: 'Faroe Islands', iso2: 'FO', dialCode: '+298'),
  CountryCode(name: 'Fiji', iso2: 'FJ', dialCode: '+679'),
  CountryCode(name: 'Finland', iso2: 'FI', dialCode: '+358'),
  CountryCode(name: 'France', iso2: 'FR', dialCode: '+33'),
  CountryCode(name: 'French Guiana', iso2: 'GF', dialCode: '+594'),
  CountryCode(name: 'French Polynesia', iso2: 'PF', dialCode: '+689'),
  CountryCode(name: 'French Southern Territories', iso2: 'TF', dialCode: '+262'),
  CountryCode(name: 'Gabon', iso2: 'GA', dialCode: '+241'),
  CountryCode(name: 'Gambia', iso2: 'GM', dialCode: '+220'),
  CountryCode(name: 'Georgia', iso2: 'GE', dialCode: '+995'),
  CountryCode(name: 'Germany', iso2: 'DE', dialCode: '+49'),
  CountryCode(name: 'Ghana', iso2: 'GH', dialCode: '+233'),
  CountryCode(name: 'Gibraltar', iso2: 'GI', dialCode: '+350'),
  CountryCode(name: 'Greece', iso2: 'GR', dialCode: '+30'),
  CountryCode(name: 'Greenland', iso2: 'GL', dialCode: '+299'),
  CountryCode(name: 'Grenada', iso2: 'GD', dialCode: '+1473'),
  CountryCode(name: 'Guadeloupe', iso2: 'GP', dialCode: '+590'),
  CountryCode(name: 'Guam', iso2: 'GU', dialCode: '+1671'),
  CountryCode(name: 'Guatemala', iso2: 'GT', dialCode: '+502'),
  CountryCode(name: 'Guernsey', iso2: 'GG', dialCode: '+44'),
  CountryCode(name: 'Guinea', iso2: 'GN', dialCode: '+224'),
  CountryCode(name: 'Guinea-Bissau', iso2: 'GW', dialCode: '+245'),
  CountryCode(name: 'Guyana', iso2: 'GY', dialCode: '+592'),
  CountryCode(name: 'Haiti', iso2: 'HT', dialCode: '+509'),
  CountryCode(name: 'Heard Island and McDonald Islands', iso2: 'HM', dialCode: '+0'),
  CountryCode(name: 'Holy See (Vatican City State)', iso2: 'VA', dialCode: '+379'),
  CountryCode(name: 'Honduras', iso2: 'HN', dialCode: '+504'),
  CountryCode(name: 'Hong Kong China', iso2: 'HK', dialCode: '+852'),
  CountryCode(name: 'Hungary', iso2: 'HU', dialCode: '+36'),
  CountryCode(name: 'Iceland', iso2: 'IS', dialCode: '+354'),
  CountryCode(name: 'Indonesia', iso2: 'ID', dialCode: '+62'),
  CountryCode(name: 'Iran, Islamic Republic of', iso2: 'IR', dialCode: '+98'),
  CountryCode(name: 'Iraq', iso2: 'IQ', dialCode: '+964'),
  CountryCode(name: 'Ireland', iso2: 'IE', dialCode: '+353'),
  CountryCode(name: 'Isle of Man', iso2: 'IM', dialCode: '+44'),
  CountryCode(name: 'Israel', iso2: 'IL', dialCode: '+972'),
  CountryCode(name: 'Italy', iso2: 'IT', dialCode: '+39'),
  CountryCode(name: 'Jamaica', iso2: 'JM', dialCode: '+1876'),
  CountryCode(name: 'Japan', iso2: 'JP', dialCode: '+81'),
  CountryCode(name: 'Jersey', iso2: 'JE', dialCode: '+44'),
  CountryCode(name: 'Jordan', iso2: 'JO', dialCode: '+962'),
  CountryCode(name: 'Kazakhstan', iso2: 'KZ', dialCode: '+7'),
  CountryCode(name: 'Kenya', iso2: 'KE', dialCode: '+254'),
  CountryCode(name: 'Kiribati', iso2: 'KI', dialCode: '+686'),
  CountryCode(name: 'Kosovo', iso2: 'XK', dialCode: '+383'),
  CountryCode(name: 'Kuwait', iso2: 'KW', dialCode: '+965'),
  CountryCode(name: 'Kyrgyzstan', iso2: 'KG', dialCode: '+996'),
  CountryCode(name: 'Lao People\'s Democratic Republic', iso2: 'LA', dialCode: '+856'),
  CountryCode(name: 'Latvia', iso2: 'LV', dialCode: '+371'),
  CountryCode(name: 'Lebanon', iso2: 'LB', dialCode: '+961'),
  CountryCode(name: 'Lesotho', iso2: 'LS', dialCode: '+266'),
  CountryCode(name: 'Liberia', iso2: 'LR', dialCode: '+231'),
  CountryCode(name: 'Libya', iso2: 'LY', dialCode: '+218'),
  CountryCode(name: 'Liechtenstein', iso2: 'LI', dialCode: '+423'),
  CountryCode(name: 'Lithuania', iso2: 'LT', dialCode: '+370'),
  CountryCode(name: 'Luxembourg', iso2: 'LU', dialCode: '+352'),
  CountryCode(name: 'Macao China', iso2: 'MO', dialCode: '+853'),
  CountryCode(name: 'Madagascar', iso2: 'MG', dialCode: '+261'),
  CountryCode(name: 'Malawi', iso2: 'MW', dialCode: '+265'),
  CountryCode(name: 'Malaysia', iso2: 'MY', dialCode: '+60'),
  CountryCode(name: 'Maldives', iso2: 'MV', dialCode: '+960'),
  CountryCode(name: 'Mali', iso2: 'ML', dialCode: '+223'),
  CountryCode(name: 'Malta', iso2: 'MT', dialCode: '+356'),
  CountryCode(name: 'Marshall Islands', iso2: 'MH', dialCode: '+692'),
  CountryCode(name: 'Martinique', iso2: 'MQ', dialCode: '+596'),
  CountryCode(name: 'Mauritania', iso2: 'MR', dialCode: '+222'),
  CountryCode(name: 'Mauritius', iso2: 'MU', dialCode: '+230'),
  CountryCode(name: 'Mayotte', iso2: 'YT', dialCode: '+262'),
  CountryCode(name: 'Mexico', iso2: 'MX', dialCode: '+52'),
  CountryCode(name: 'Micronesia, Federated States of', iso2: 'FM', dialCode: '+691'),
  CountryCode(name: 'Moldova, Republic of', iso2: 'MD', dialCode: '+373'),
  CountryCode(name: 'Monaco', iso2: 'MC', dialCode: '+377'),
  CountryCode(name: 'Mongolia', iso2: 'MN', dialCode: '+976'),
  CountryCode(name: 'Montenegro', iso2: 'ME', dialCode: '+382'),
  CountryCode(name: 'Montserrat', iso2: 'MS', dialCode: '+1664'),
  CountryCode(name: 'Morocco', iso2: 'MA', dialCode: '+212'),
  CountryCode(name: 'Mozambique', iso2: 'MZ', dialCode: '+258'),
  CountryCode(name: 'Myanmar', iso2: 'MM', dialCode: '+95'),
  CountryCode(name: 'Namibia', iso2: 'NA', dialCode: '+264'),
  CountryCode(name: 'Nauru', iso2: 'NR', dialCode: '+674'),
  CountryCode(name: 'Nepal', iso2: 'NP', dialCode: '+977'),
  CountryCode(name: 'Netherlands', iso2: 'NL', dialCode: '+31'),
  CountryCode(name: 'New Caledonia', iso2: 'NC', dialCode: '+687'),
  CountryCode(name: 'New Zealand', iso2: 'NZ', dialCode: '+64'),
  CountryCode(name: 'Nicaragua', iso2: 'NI', dialCode: '+505'),
  CountryCode(name: 'Niger', iso2: 'NE', dialCode: '+227'),
  CountryCode(name: 'Nigeria', iso2: 'NG', dialCode: '+234'),
  CountryCode(name: 'Niue', iso2: 'NU', dialCode: '+683'),
  CountryCode(name: 'Norfolk Island', iso2: 'NF', dialCode: '+672'),
  CountryCode(name: 'North Korea', iso2: 'KP', dialCode: '+850'),
  CountryCode(name: 'North Macedonia, Republic of', iso2: 'MK', dialCode: '+389'),
  CountryCode(name: 'Northern Mariana Islands', iso2: 'MP', dialCode: '+1670'),
  CountryCode(name: 'Norway', iso2: 'NO', dialCode: '+47'),
  CountryCode(name: 'Oman', iso2: 'OM', dialCode: '+968'),
  CountryCode(name: 'Pakistan', iso2: 'PK', dialCode: '+92'),
  CountryCode(name: 'Palau', iso2: 'PW', dialCode: '+680'),
  CountryCode(name: 'Palestine', iso2: 'PS', dialCode: '+970'),
  CountryCode(name: 'Panama', iso2: 'PA', dialCode: '+507'),
  CountryCode(name: 'Papua New Guinea', iso2: 'PG', dialCode: '+675'),
  CountryCode(name: 'Paraguay', iso2: 'PY', dialCode: '+595'),
  CountryCode(name: 'Peru', iso2: 'PE', dialCode: '+51'),
  CountryCode(name: 'Philippines', iso2: 'PH', dialCode: '+63'),
  CountryCode(name: 'Pitcairn', iso2: 'PN', dialCode: '+64'),
  CountryCode(name: 'Poland', iso2: 'PL', dialCode: '+48'),
  CountryCode(name: 'Portugal', iso2: 'PT', dialCode: '+351'),
  CountryCode(name: 'Puerto Rico', iso2: 'PR', dialCode: '+1939'),
  CountryCode(name: 'Qatar', iso2: 'QA', dialCode: '+974'),
  CountryCode(name: 'Reunion', iso2: 'RE', dialCode: '+262'),
  CountryCode(name: 'Romania', iso2: 'RO', dialCode: '+40'),
  CountryCode(name: 'Russia', iso2: 'RU', dialCode: '+7'),
  CountryCode(name: 'Rwanda', iso2: 'RW', dialCode: '+250'),
  CountryCode(name: 'Saint Barthélemy', iso2: 'BL', dialCode: '+590'),
  CountryCode(name: 'Saint Helena', iso2: 'SH', dialCode: '+290'),
  CountryCode(name: 'Saint Kitts and Nevis', iso2: 'KN', dialCode: '+1869'),
  CountryCode(name: 'Saint Lucia', iso2: 'LC', dialCode: '+1758'),
  CountryCode(name: 'Saint Martin (French part)', iso2: 'MF', dialCode: '+590'),
  CountryCode(name: 'Saint Pierre and Miquelon', iso2: 'PM', dialCode: '+508'),
  CountryCode(name: 'Saint Vincent and the Grenadines', iso2: 'VC', dialCode: '+1784'),
  CountryCode(name: 'Samoa', iso2: 'WS', dialCode: '+685'),
  CountryCode(name: 'San Marino', iso2: 'SM', dialCode: '+378'),
  CountryCode(name: 'Sao Tome and Principe', iso2: 'ST', dialCode: '+239'),
  CountryCode(name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966'),
  CountryCode(name: 'Senegal', iso2: 'SN', dialCode: '+221'),
  CountryCode(name: 'Serbia', iso2: 'RS', dialCode: '+381'),
  CountryCode(name: 'Seychelles', iso2: 'SC', dialCode: '+248'),
  CountryCode(name: 'Sierra Leone', iso2: 'SL', dialCode: '+232'),
  CountryCode(name: 'Singapore', iso2: 'SG', dialCode: '+65'),
  CountryCode(name: 'Slovakia', iso2: 'SK', dialCode: '+421'),
  CountryCode(name: 'Slovenia', iso2: 'SI', dialCode: '+386'),
  CountryCode(name: 'Solomon Islands', iso2: 'SB', dialCode: '+677'),
  CountryCode(name: 'Somalia', iso2: 'SO', dialCode: '+252'),
  CountryCode(name: 'South Africa', iso2: 'ZA', dialCode: '+27'),
  CountryCode(name: 'South Georgia and the South Sandwich Islands', iso2: 'GS', dialCode: '+500'),
  CountryCode(name: 'South Korea', iso2: 'KR', dialCode: '+82'),
  CountryCode(name: 'South Sudan', iso2: 'SS', dialCode: '+211'),
  CountryCode(name: 'Spain', iso2: 'ES', dialCode: '+34'),
  CountryCode(name: 'Sri Lanka', iso2: 'LK', dialCode: '+94'),
  CountryCode(name: 'Sudan', iso2: 'SD', dialCode: '+249'),
  CountryCode(name: 'Suriname', iso2: 'SR', dialCode: '+597'),
  CountryCode(name: 'Svalbard and Jan Mayen', iso2: 'SJ', dialCode: '+47'),
  CountryCode(name: 'Sweden', iso2: 'SE', dialCode: '+46'),
  CountryCode(name: 'Switzerland', iso2: 'CH', dialCode: '+41'),
  CountryCode(name: 'Syrian Arab Republic', iso2: 'SY', dialCode: '+963'),
  CountryCode(name: 'Taiwan China', iso2: 'TW', dialCode: '+886'),
  CountryCode(name: 'Tajikistan', iso2: 'TJ', dialCode: '+992'),
  CountryCode(name: 'Tanzania, United Republic of', iso2: 'TZ', dialCode: '+255'),
  CountryCode(name: 'Thailand', iso2: 'TH', dialCode: '+66'),
  CountryCode(name: 'Timor-Leste', iso2: 'TL', dialCode: '+670'),
  CountryCode(name: 'Togo', iso2: 'TG', dialCode: '+228'),
  CountryCode(name: 'Tokelau', iso2: 'TK', dialCode: '+690'),
  CountryCode(name: 'Tonga', iso2: 'TO', dialCode: '+676'),
  CountryCode(name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '+1868'),
  CountryCode(name: 'Tunisia', iso2: 'TN', dialCode: '+216'),
  CountryCode(name: 'Turkey', iso2: 'TR', dialCode: '+90'),
  CountryCode(name: 'Turkmenistan', iso2: 'TM', dialCode: '+993'),
  CountryCode(name: 'Turks and Caicos Islands', iso2: 'TC', dialCode: '+1649'),
  CountryCode(name: 'Tuvalu', iso2: 'TV', dialCode: '+688'),
  CountryCode(name: 'Uganda', iso2: 'UG', dialCode: '+256'),
  CountryCode(name: 'Ukraine', iso2: 'UA', dialCode: '+380'),
  CountryCode(name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971'),
  CountryCode(name: 'United Kingdom', iso2: 'GB', dialCode: '+44'),
  CountryCode(name: 'Uruguay', iso2: 'UY', dialCode: '+598'),
  CountryCode(name: 'Uzbekistan', iso2: 'UZ', dialCode: '+998'),
  CountryCode(name: 'Vanuatu', iso2: 'VU', dialCode: '+678'),
  CountryCode(name: 'Venezuela', iso2: 'VE', dialCode: '+58'),
  CountryCode(name: 'Vietnam', iso2: 'VN', dialCode: '+84'),
  CountryCode(name: 'Virgin Islands, British', iso2: 'VG', dialCode: '+1284'),
  CountryCode(name: 'Virgin Islands, U.S.', iso2: 'VI', dialCode: '+1340'),
  CountryCode(name: 'Wallis and Futuna', iso2: 'WF', dialCode: '+681'),
  CountryCode(name: 'Yemen', iso2: 'YE', dialCode: '+967'),
  CountryCode(name: 'Zambia', iso2: 'ZM', dialCode: '+260'),
  CountryCode(name: 'Zimbabwe', iso2: 'ZW', dialCode: '+263'),
  CountryCode(name: 'Åland Islands', iso2: 'AX', dialCode: '+358'),
];
