// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAES3UFzJueXEmjnBCBWWLvT4wZAeZUEbQ',
    appId: '1:1098077986035:web:6c4ed793308b2b7ae7ab86',
    messagingSenderId: '1098077986035',
    projectId: 'alphabetgreens',
    authDomain: 'alphabetgreens.firebaseapp.com',
    storageBucket: 'alphabetgreens.appspot.com',
    measurementId: 'G-C1R3N2CN4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC20__1AV6bVnSiqKaZkZRO7yx19IrDMA0',
    appId: '1:1098077986035:android:70f4ef1b7c68ac29e7ab86',
    messagingSenderId: '1098077986035',
    projectId: 'alphabetgreens',
    storageBucket: 'alphabetgreens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iJKQ7yCRH9aIaSaAE3LfKD7yJb11ybs',
    appId: '1:1098077986035:ios:7d10d6730d52c788e7ab86',
    messagingSenderId: '1098077986035',
    projectId: 'alphabetgreens',
    storageBucket: 'alphabetgreens.appspot.com',
    iosClientId:
        '1098077986035-4v68t957erttkm7skggetjvg59v0q6gt.apps.googleusercontent.com',
    iosBundleId: 'com.alphabetgreenenergy.alphabetGreenEnergy',
  );
}
